-- No-op compatibility shim.
--
-- The production project recorded this migration as
-- 20260430073814_set_free_starter_tokens_to_100. That canonical SQL now lives
-- in the matching file under that timestamp. Keeping this later timestamp as a
-- no-op avoids double-applying the same data patch in environments that only
-- know about the 20260430090000 filename.
